---
- name: install packages
  package:
    name:
      - samba
      - samba-common
      - krb5-user
      - krb5-config
      - winbind
      - libpam-winbind
    state: present

- name: template /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0600

- name: template /etc/samba/smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0600
  notify: restart smbd

#- name: /etc/hosts
#  template:
#    src: hosts.j2
#    dest: /etc/hosts

#- hostname:
#    name: proaluno4.smbdomain.fflch.usp.br

- name: "Joining to domain"
  shell: "net ads join -U Administrator%{{ domain_member_password }}"

- name: Restart service nmbd
  service:
    name: nmbd
    state: restarted

- name: Restart service smbd
  service:
    name: smbd
    state: restarted

- name: Restart service winbind
  service:
    name: winbind
    state: restarted
